
trigger: 
  - master

pool:
  name: Default

stages:
  - stage: CheckoutCode
    jobs:
      - job: 'Checkoutgitcode'
        steps:
          - checkout: self
  - stage: 'Build'   
    jobs:
      - job: 'BuildJob'
        steps:   
          - task: Maven@4
            inputs:
             mavenPomFile: 'pom.xml'
             goals: 'install'
             publishJUnitResults: false
             javaHomeOption: 'JDKVersion'
             mavenVersionOption: 'Default'
             mavenAuthenticateFeed: false
             effectivePomSkip: false
             sonarQubeRunAnalysis: false
      
  - stage:  'PublishArtifact_stage'
    jobs:
      - job: 'Publish_artifactjob'
        steps:
        - task: PublishPipelineArtifact@1
          inputs:
           targetPath: '$(Pipeline.Workspace)'
           artifact: 'DemoArtifactYamL'
           publishLocation: 'pipeline'
  - stage: 'Downloadartifact'        
    jobs:
       - deployment: Deploy
         environment: Stage
         strategy: 
          runOnce:
             deploy:
                steps:
                 - task: DownloadPipelineArtifact@2
                   inputs:
                    buildType: 'specific'
                    project: 'b50a6f14-b67d-4ae8-84dc-73b166eb7cb7'
                    definition: '98'
                    buildVersionToDownload: 'latest'
                    artifactName: 'DemoArtifactYaml'
                    targetPath: '$(Pipeline.Workspace)'
  - stage: 'DeploywithSSH'
    jobs:
      - job: "DeployoverSSH" 
        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'TomcatScForazurepipeline'
              runOptions: 'inline'
              inline: |
                     echo "Hello"
                     sudo cp /opt/myagent/_work/1/s/target/StudentLoginFormyaml.war  /opt/tomcat/webapps
         
                    